language: node_js
node_js: node
deploy:
  provider: heroku
  api_key:
    secure: fH5tkQCWaAEysKpsV+SfJ/SsrPL9HMQd2ThcfApMaUMyxsn3Ns3nh6O9Lr7XFWUmksNDMQp0scLKlm5F5UzHUEdiZOVas+ULyFORtysJjKCueWXFrBJJvoNzA+ifg4+byf2NZcmFy+tsfSkk7ykZn7mMnX5M6Bknm9d4yPdfTsiacArgA1idS/abbS1rjzxl2d307pgZQ+kDbeFm2ZG5n39pXdR8DHSsjyg/ut1sa4b48EAPLLJSX/p27Rw37dhWHXlaMkZx5Nq7Gafp5zpY7fMBS5p2nMyV6VdZ2YQZMnf7iwCZVWD6X9OEGsLXW134JT5F5Xm69rEQgQSbq+gvyzaP+6aJFmgcMlQQiDAXuIuB1P9mtO2MlPsESTpwGB6CiG44UPN5JeULsSU60gYQt8UW8DYxYpDdeTWF6jqvAMSXCS2BE4sN0Ely4Y5IAox0xWNADeSKdSkwgIj/egjjjW3VkEe9H7fK75ey/MbedODY2RFQ4YoKDgB5nSwvU1RczVYy96rxph1rMo56bQsrMdsaJvZ9DpUPMkHrEPnr7ihq1InMSaQKqp0NeP9VVmjIntthNxeGSBEbzSmVxS1UAgHQ9R73cL/t4MchI7elv6R6ByNeMoorMkicUsRLvu+giyVOf+tctdSF6IIjfuAy8DLLicOCc+TJRsUWiJahaEs=
  app: node-capstone
  on:
    repo: CryptoCoinUser/node-capstone
